//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNGMTTNanoTracker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracao
    {
        public string Chave { get; set; }
        public string Valor { get; set; }
        public int ConfiguracaoID { get; set; }
    }
}
