//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNGMTTNanoTracker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesas
    {
        public string Table { get; set; }
        public string NomeAmigavel { get; set; }
        public string Players { get; set; }
        public int MesaID { get; set; }
    }
}
