//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNGMTTNanoTracker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultados
    {
        public int ResultadoID { get; set; }
        public System.DateTime Inicio { get; set; }
        public System.DateTime Fim { get; set; }
        public string Mesa { get; set; }
        public decimal BuyInRake { get; set; }
        public int Posicao { get; set; }
        public decimal Winning { get; set; }
        public int TorneioID { get; set; }
        public string Jogadores { get; set; }
        public Nullable<decimal> Rebuy { get; set; }
        public Nullable<decimal> AddOn { get; set; }
        public Nullable<decimal> Knockout { get; set; }
    }
}
